### PR TITLE
new X-at-point whichs allow all non-blank char

### PR DESCRIPTION
**Pull request by yuchen-lea**
This commit changes `symbol-at-point` as you suuggested to support all non-blank char as keyword, including `<` of course.

related Issue: https://github.com/Kungsgeten/yankpad/issues/67

First time to do this on github, if I did anything inappropriate, just tell me ;)

### CODE REVIEW

**Comment by isamert** [comment]
I tried this patch and it works quite fine. Currently I'm using yasnippet snippets alongside with yankpad because yankpad does not support keywords with non-ascii chars while yasnippet supports it. Any reason for not including this @Kungsgeten?

**Comment by Kungsgeten** [comment]
@isamert I intended to try this patch but then forgot about it. The submitted code needs some minor tweaks in order to conform with the Emacs Lisp code standards, but otherwise there's no reason not to include it (if it works). I've recently moved to a new apartment and will be a first time father in about a month, so unfortunately my Emacs packages have a lower priority at the moment.

**Comment by isamert** [comment]
I see, thanks! Just wanted to give you a friendly nudge.

I'm aware that it needs minor tweaks (and some edge cases might need handling, I saw a minor issue while using it). Maybe @yuchen-lea can clear things up (and I can give some feedback), or I can also just clear things up to ease up your work. No rush tho, I patched in my local and using it. Seems like you are not going to do much with this package for a while, so there is no maintenance burden on my side.

Oh, by the way, congratulations on being father!

**Comment by Kungsgeten** [comment]
Seems to work fine, though I will refactor a bit and fix an issue I noticed (not related to the PR).

**Pull request merged**
